export const productFormulas = {
    'SABIA ESPECIAL': [
        { name: 'PRESENCE(EXTRAMUDA)', quantity: 300 },
        { name: 'CASTANHA TRITURADA MEDIA', quantity: 90 },
        { name: 'AMENDOIM QUEBRADO', quantity: 20 },
        { name: 'OLEO VEGETAL', quantity: 29.5 },
        { name: '(PREMIX)BISCOITO MÉDIO', quantity: 60 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 0.5 },
    ],
    'CAMPINA ESPECIAL': [
        { name: 'ALPISTE', quantity: 150 },
        { name: 'ARROZ C/CASCA', quantity: 45 },
        { name: 'AVEIA SEM CASCA', quantity: 10 },
        { name: 'PAINÇO COMUM', quantity: 100 },
        { name: 'PAINÇO VERMELHO', quantity: 5 },
        { name: 'PAINÇO VERDE', quantity: 5 },
        { name: 'PAINÇO PRETO', quantity: 5 },
        { name: 'XEREM FINO', quantity: 30 },
        { name: 'MILHETO', quantity: 45 },
        { name: 'COLZA', quantity: 30 },
        { name: 'SENHA', quantity: 10 },
        { name: '(PREMIX)BISCOITO FINO', quantity: 60 },
        { name: 'OLEO VEGETAL', quantity: 4.5 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 0.5 },
    ],
    'BELGA ESPECIAL': [
        { name: 'ALPISTE', quantity: 170 },
        { name: 'COLZA', quantity: 70 },
        { name: 'AVEIA SEM CASCA', quantity: 70 },
        { name: 'NIGER', quantity: 5 },
        { name: 'NABÃO', quantity: 30 },
        { name: 'PAINÇO COMUM', quantity: 53 },
        { name: 'LINHAÇA', quantity: 30 },
        { name: 'VITAMINA AMARELA', quantity: 0 },
        { name: 'MILHETO', quantity: 40 },
        { name: '(PREMIX)BISCOITO FINO', quantity: 30 },
        { name: 'OLEO VEGETAL', quantity: 2 },
    ],
    'CURRUPIÃO': [
        { name: 'PRESENCE(EXTRAMUDA)', quantity: 30 },
        { name: 'OLEO VEGETAL', quantity: 18 },
        { name: 'MASSA DE MILHO', quantity: 80 },
        { name: 'CASTANHA TRITURADA FINA', quantity: 15 },
        { name: 'VENTILAÇAO DE CASTANHA', quantity: 60 },
        { name: 'COLORIFICO', quantity: 3 },
        { name: '(PREMIX)BISCOITO FINO', quantity: 35 },
        { name: 'SAL FINO', quantity: 3 },
        { name: 'FRUTAS CRISTALIZADAS', quantity: 5 },
    ],
    'CURIO': [
        { name: 'ALPISTE', quantity: 75 },
        { name: 'ARROZ C/CASCA', quantity: 30 },
        { name: 'NIGER', quantity: 20 },
        { name: 'PAINÇO COMUM', quantity: 50 },
        { name: 'MILHETO', quantity: 10 },
        { name: '(PREMIX)BISCOITO FINO', quantity: 30 },
        { name: 'PAINÇO VERDE', quantity: 50 },
        { name: 'PAINÇO PRETO', quantity: 75 },
        { name: 'PAINÇO VERMELHO', quantity: 100 },
        { name: 'PAINÇO PORTUGUES', quantity: 10 },
        { name: 'SENHA', quantity: 10 },
        { name: 'XEREM FINO', quantity: 10 },
        { name: 'GIRASSOL CARTAMO', quantity: 15 },
        { name: 'OLEO VEGETAL', quantity: 12.5 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 2.5 },
    ],
    'VIT AMARELA': [
        { name: 'XEREM FINO', quantity: 359 },
        { name: 'LINHAÇA', quantity: 24 },
        { name: 'NABÃO', quantity: 23.5 },
        { name: 'AROMA ARTIFICIAL', quantity: 2 },
        { name: 'AVEIA SEM CASCA', quantity: 24 },
        { name: 'COLZA', quantity: 24 },
        { name: 'OLEO VEGETAL', quantity: 43 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 0.5 },
    ],
    'GRAUNA ESPECIAL': [
        { name: 'ARROZ C/CASCA', quantity: 50 },
        { name: 'CASTANHA TRITURADA MEDIA', quantity: 44 },
        { name: 'AMENDOIM QUEBRADO', quantity: 20 },
        { name: 'XEREM GROSSO', quantity: 10 },
        { name: 'SORGO VERMELHO', quantity: 20 },
        { name: 'SORGO BRANCO', quantity: 20 },
        { name: 'GIRASSOL CARTAMO', quantity: 6 },
        { name: 'PRESENCE(EXTRAMUDA)', quantity: 250 },
        { name: 'OLEO VEGETAL', quantity: 19 },
        { name: '(PREMIX)BISCOITO MÉDIO', quantity: 60 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 1 },
    ],
    'CALOPSITA': [
        { name: 'ALPISTE', quantity: 45 },
        { name: 'ARROZ C/CASCA', quantity: 25 },
        { name: 'XEREM GROSSO', quantity: 15 },
        { name: 'PAINÇO COMUM', quantity: 35 },
        { name: 'SORGO VERMELHO', quantity: 30 },
        { name: 'SORGO BRANCO', quantity: 25 },
        { name: 'GIRASSOL PEQUENO', quantity: 100 },
        { name: 'CASTANHA TRITURADA FINA', quantity: 0.5 },
        { name: 'AVEIA COM CASCA', quantity: 55 },
        { name: 'ERVILHA QUEBRADA', quantity: 30 },
        { name: 'MILHETO', quantity: 25 },
        { name: 'NABÃO', quantity: 20 },
        { name: 'AVEIA SEM CASCA', quantity: 25 },
        { name: 'GIRASSOL CARTAMO', quantity: 20 },
        { name: 'OLEO VEGETAL', quantity: 4.5 },
        { name: '(PREMIX)BISCOITO MÉDIO', quantity: 45 },
    ],
    'GALO ESPECIAL': [
        { name: 'AMENDOIM SEM CASCA', quantity: 25 },
        { name: 'ARROZ C/CASCA', quantity: 40 },
        { name: 'AVEIA COM CASCA', quantity: 30 },
        { name: 'OLEO VEGETAL', quantity: 4.5 },
        { name: 'ERVILHA INTEIRA P/RACAO', quantity: 15 },
        { name: 'ERVILHA QUEBRADA', quantity: 20 },
        { name: 'PRESENCE(EXTRAMUDA)', quantity: 20 },
        { name: 'PROEQUI(EQUIMIX)', quantity: 40 },
        { name: 'GIRASSOL PEQUENO', quantity: 40 },
        { name: 'SOJA GRÃO', quantity: 50 },
        { name: 'SORGO VERMELHO', quantity: 65 },
        { name: 'SORGO BRANCO', quantity: 25 },
        { name: 'TRIGUILHO', quantity: 35 },
        { name: 'MILHO EM GRÃO', quantity: 10 },
        { name: 'XEREM GROSSO', quantity: 50 },
        { name: '(PREMIX)BISCOITO GROSSO', quantity: 30 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 0.5 },
    ],
    'PAPAGAIO ESPECIAL': [
        { name: 'AMENDOIM SEM CASCA', quantity: 30 },
        { name: 'AMENDOIM COM CASCA', quantity: 50 },
        { name: 'XEREM GROSSO', quantity: 40 },
        { name: 'MILHO EM GRÃO', quantity: 10 },
        { name: 'CASTANHA TRITURADA MEDIA', quantity: 80 },
        { name: 'SEMENTE GIRASSOL GRANDE', quantity: 150 },
        { name: 'AVEIA COM CASCA', quantity: 50 },
        { name: 'AVEIA SEM CASCA', quantity: 10 },
        { name: 'ERVILHA QUEBRADA', quantity: 15 },
        { name: 'ERVILHA INTEIRA P/RACAO', quantity: 10 },
        { name: 'OLEO VEGETAL', quantity: 4.5 },
        { name: 'TRIGUILHO', quantity: 15 },
        { name: '(PREMIX)BISCOITO GROSSO', quantity: 45 },
        { name: 'ANTI-MOFO (AMMO CURB)', quantity: 0.5 },
    ],
    'MISTURA FINA COMUM': [
        { name: 'ALPISTE', quantity: 70 },
        { name: 'PAINÇO COMUM', quantity: 215 },
        { name: 'MILHETO', quantity: 100 },
        { name: 'XEREM FINO', quantity: 55 },
        { name: 'COLZA', quantity: 5 },
        { name: 'SENHA', quantity: 5 },
        { name: 'PAINÇO PRETO', quantity: 8 },
        { name: 'PAINÇO VERMELHO', quantity: 10 },
        { name: '(PREMIX)BISCOITO FINO', quantity: 30 },
        { name: 'OLEO VEGETAL', quantity: 2 },
    ],
};
export const products = [
    { name: 'SABIA COMUM', costPerKg: 2.53, sellPricePerKg: 3.89 },
    { name: 'SABIA ESPECIAL', costPerKg: 2.79, sellPricePerKg: 4.29 },
    { name: 'NOVO SABIA ESPECIAL', costPerKg: 1.97, sellPricePerKg: 3.03 },
    { name: 'CAMPINA COMUM', costPerKg: 4.27, sellPricePerKg: 6.57 },
    { name: 'CAMPINA ESPECIAL', costPerKg: 5.16, sellPricePerKg: 7.94 },
    { name: 'NOVA CAMPINA ESPECIAL', costPerKg: 3.10, sellPricePerKg: 4.77 },
    { name: 'BELGA COMUM', costPerKg: 5.22, sellPricePerKg: 8.03 },
    { name: 'BELGA ESPECIAL', costPerKg: 5.78, sellPricePerKg: 8.89 },
    { name: 'NOVO BELGA ESPECIAL', costPerKg: 5.00, sellPricePerKg: 7.70 },
    { name: 'CURRUPIAO', costPerKg: 1.84, sellPricePerKg: 2.83 },
    { name: 'CURIO', costPerKg: 5.77, sellPricePerKg: 8.88 },
    { name: 'VITAMINA AMARELA', costPerKg: 2.13, sellPricePerKg: 3.27 },
    { name: 'GRAUNA COMUM', costPerKg: 2.83, sellPricePerKg: 4.35 },
    { name: 'GRAUNA ESPECIAL', costPerKg: 3.10, sellPricePerKg: 4.77 },
    { name: 'CALOPSITA', costPerKg: 4.35, sellPricePerKg: 6.68 },
    { name: 'GALO COMUM', costPerKg: 2.90, sellPricePerKg: 4.47 },
    { name: 'GALO ESPECIAL', costPerKg: 3.46, sellPricePerKg: 5.32 },
    { name: 'NOVO GALO ESPECIAL', costPerKg: 2.80, sellPricePerKg: 4.30 },
    { name: 'PAPAGAIO ESPECIAL', costPerKg: 4.62, sellPricePerKg: 7.11 },
    { name: 'MISTURA FINA', costPerKg: 4.48, sellPricePerKg: 6.90 },
    { name: 'NOVA MISTURA FINA', costPerKg: 3.20, sellPricePerKg: 4.93 }
  ];
  
  
    export const ingredients = [
      { name: 'ALPISTE', costPerKg: 6 },
      { name: 'AMENDOIM COM CASCA', costPerKg: 6 },
      { name: 'AMENDOIM QUEBRADO', costPerKg: 6 },
      { name: 'AMENDOIM SEM CASCA', costPerKg: 6 },
      { name: 'ANTI-MOFO (AMMO CURB)', costPerKg: 16.8 },
      { name: 'AROMA ARTIFICIAL', costPerKg: 27 },
      { name: 'ARROZ C/CASCA', costPerKg: 3.95 },
      { name: 'AVEIA COM CASCA', costPerKg: 2.5 },
      { name: 'AVEIA SEM CASCA', costPerKg: 3.7 },
      { name: '(PREMIX)BISCOITO FINO', costPerKg: 6.45 },
      { name: '(PREMIX)BISCOITO MÉDIO', costPerKg: 6 },
      { name: '(PREMIX)BISCOITO GROSSO', costPerKg: 6 },
      { name: '(PREMIX)PÓ AMARELO', costPerKg: 6 },
      { name: '(PREMIX)PÓ COLORIDO', costPerKg: 6 },
      { name: 'CASTANHA TRITURADA FINA', costPerKg: 1.1 },
      { name: 'CASTANHA TRITURADA GROSSA', costPerKg: 1.1 },
      { name: 'CASTANHA TRITURADA MEDIA', costPerKg: 1.1 },
      { name: 'FAROFA DE CASTANHA', costPerKg: 1.1 },
      { name: 'FAROFA DE AMENDOIM', costPerKg: 2.05 },
      { name: 'COLZA', costPerKg: 4.6 },
      { name: 'ERVILHA INTEIRA P/RACAO', costPerKg: 3.4 },
      { name: 'ERVILHA PARTIDA P/RACAO', costPerKg: 3.75 },
      { name: 'PRESENCE(EXTRAMUDA)', costPerKg: 2 },
      { name: 'PRESENCE(BANANA)', costPerKg: 2 },
      { name: 'PRESENCE(BANANA TRITURADA)', costPerKg: 2 },
      { name: 'LINHAÇA', costPerKg: 6.9 },
      { name: 'MILHETO', costPerKg: 1 },
      { name: 'MILHO EM GRÃO', costPerKg: 0.85 },
      { name: 'NABÃO', costPerKg: 4.3 },
      { name: 'NIGER', costPerKg: 9.2 },
      { name: 'OLEO VEGETAL', costPerKg: 2 },
      { name: 'OLEO DE SOJA', costPerKg: 2 },
      { name: 'PAINÇO COMUM', costPerKg: 5.35 },
      { name: 'PAINÇO PRETO', costPerKg: 6 },
      { name: 'PAINÇO VERDE', costPerKg: 4.55 },
      { name: 'PAINÇO VERMELHO', costPerKg: 6 },
      { name: 'PAINÇO PORTUGUES', costPerKg: 5.8 },
      { name: 'PREFRAN', costPerKg: 0 },
      { name: 'PROEQUI(MELAÇADA)', costPerKg: 1.2 },
      { name: 'PROEQUI(EQUIMIX)', costPerKg: 1.2 },
      { name: 'GIRASSOL PEQUENO', costPerKg: 5.7 },
      { name: 'SEMENTE GIRASSOL GRANDE', costPerKg: 5.9 },
      { name: 'SENHA FRANCESA', costPerKg: 6.35 },
      { name: 'SOJA GRÃO', costPerKg: 4.5 },
      { name: 'SORGO BRANCO', costPerKg: 2.3 },
      { name: 'SORGO VERMELHO', costPerKg: 1.7 },
      { name: 'TRIGO SARRACENO', costPerKg: 2.6 },
      { name: 'TRIGUILHO', costPerKg: 1.6 },
      { name: 'VITAMINA AMARELA', costPerKg: 5.2 },
      { name: 'XEREM FINO', costPerKg: 0.8 },
      { name: 'XEREM GROSSO', costPerKg: 0.8 },
      { name: 'MASSA DE MILHO', costPerKg: 0.8 },
      { name: 'SAL COMUM', costPerKg: 0.6 }
    ];